sudo: false

language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

os:
  - linux

env:
  global:
    - DB_URL="http://browscap.org/stream?q=BrowsCapCSV"
    - TMP_PATH=test/tmp.csv
    - DB_PATH=test/browscap.csv
  matrix:
    - CPU=8

script:
  - wget $DB_URL -O $TMP_PATH
  - sed -i '1,4d' $TMP_PATH
  - sed '1,106000d' $TMP_PATH | head -300 > $DB_PATH
  - go test -v -cpu=$CPU -benchmem -bench=.

matrix:
  allow_failures:
    - go: tip
