sudo: false

language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

env:
  global:
    - DB_URL="http://browscap.org/stream?q=BrowsCapCSV"
    - DB_PATH=test/browscap.csv
  matrix:
    - CPU=1
    - CPU=8

script:
  - wget $DB_URL -O $DB_PATH
  - sed -i '1,4d' $DB_PATH
  - go test -v cpu=$CPU -benchmem -bench=.
